name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Hey @${{ github.actor }}! Thanks for opening this issue and helping us improve.  
          We appreciate your input, and our team will review this soon.  
          Stay tuned for updates, and feel free to share any further details you think might help!
        pr-message: |
          🎉 Awesome work, @${{ github.actor }}! Thank you for submitting a pull request to enhance this project.  
          Our maintainers will review it shortly. Meanwhile, let us know if there's anything you'd like to highlight about your contribution.  
          We’re thrilled to have your support in making this project even better!
